var recipes = [
    {
        id: 1,
        titre: "Boeuf Bourguignon Traditionnel",
        description: "Un grand classique de la cuisine française, mijoté longuement dans une sauce au vin rouge.",
        temps: 180,
        difficulte: "Moyen",
        emoji: "🥘",
        ingredients: [
            { nom: "boeuf", obligatoire: true },
            { nom: "vin rouge (Bourgogne)", obligatoire: true },
            { nom: "lardons", obligatoire: true },
            { nom: "carottes", obligatoire: true },
            { nom: "oignons", obligatoire: true },
            { nom: "champignons de Paris", obligatoire: false }
        ],
        ustensiles: ["cocotte en fonte", "couteau"],
        tags: ["classique", "mijote", "dimanche"],
        instructions: [
            "Coupez la viande en gros cubes et faites-les dorer dans la cocotte.",
            "Ajoutez les oignons et les lardons, faites revenir 5 minutes.",
            "Versez le vin rouge et complétez avec un peu d'eau si nécessaire.",
            "Ajoutez les carottes en rondelles et le bouquet garni.",
            "Laissez mijoter à feu très doux pendant au moins 3 heures.",
            "Servez idéalement le lendemain."
        ]
    },
    {
        id: 2,
        titre: "Blanquette de Veau à l'Ancienne",
        description: "Une viande tendre nappée d'une sauce blanche onctueuse aux petits champignons.",
        temps: 90,
        difficulte: "Moyen",
        emoji: "🍲",
        ingredients: [
            { nom: "veau", obligatoire: true },
            { nom: "carottes", obligatoire: true },
            { nom: "poireau", obligatoire: true },
            { nom: "champignons", obligatoire: true },
            { nom: "crème fraîche", obligatoire: true },
            { nom: "oeufs", obligatoire: true }
        ],
        ustensiles: ["casserole", "fouet"],
        tags: ["traditionnel", "réconfort"],
        instructions: [
            "Faites blanchir la viande dans l'eau bouillante pendant 2 minutes.",
            "Égouttez et remettez dans la casserole avec les carottes et le poireau.",
            "Couvrez d'eau et laissez mijoter 1h30.",
            "Préparez la liaison : mélangez la crème et les jaunes d'oeufs.",
            "Hors du feu, ajoutez la liaison et les champignons déjà poêlés.",
            "Servez avec du riz blanc."
        ]
    },
    {
        id: 3,
        titre: "Poulet Rôti et Pommes de Terre",
        description: "Le poulet du dimanche, à la peau bien croustillante et aux pommes de terre fondantes.",
        temps: 75,
        difficulte: "Facile",
        emoji: "🍗",
        ingredients: [
            { nom: "poulet entier", obligatoire: true },
            { nom: "pommes de terre", obligatoire: true },
            { nom: "beurre", obligatoire: true },
            { nom: "ail", obligatoire: true },
            { nom: "thym", obligatoire: false }
        ],
        ustensiles: ["plat à four", "four"],
        tags: ["familial", "rôti"],
        instructions: [
            "Préchauffez le four à 200°C.",
            "Badigeonnez le poulet de beurre et poudrez d'herbes.",
            "Disposez les pommes de terre coupées autour du poulet.",
            "Ajoutez des gousses d'ail non épluchées.",
            "Enfournez pour environ 1h15 en arrosant régulièrement.",
            "Laissez reposer 10 min avant de découper."
        ]
    },
    {
        id: 4,
        titre: "Ratatouille Provençale fondante",
        description: "Un mélange de légumes d'été confits à l'huile d'olive.",
        temps: 60,
        difficulte: "Facile",
        emoji: "🥘",
        ingredients: [
            { nom: "aubergines", obligatoire: true },
            { nom: "courgettes", obligatoire: true },
            { nom: "poivrons", obligatoire: true },
            { nom: "tomates", obligatoire: true },
            { nom: "oignons", obligatoire: true },
            { nom: "huile d'olive", obligatoire: true }
        ],
        ustensiles: ["sauteuse", "couteau"],
        tags: ["végétarien", "estival", "santé"],
        instructions: [
            "Coupez tous les légumes en dés.",
            "Faites-les revenir séparément dans l'huile d'olive.",
            "Réunissez tout dans la cocotte.",
            "Laissez mijoter à feu doux pendant au moins 1 heure."
        ]
    },
    {
        id: 5,
        titre: "Gratin Dauphinois Fondant",
        description: "Des pommes de terre fondantes dans de la crème, sans fromage (la vraie recette !).",
        temps: 80,
        difficulte: "Facile",
        emoji: "🥘",
        ingredients: [
            { nom: "pommes de terre", obligatoire: true },
            { nom: "crème fraîche", obligatoire: true },
            { nom: "lait", obligatoire: true },
            { nom: "ail", obligatoire: true },
            { nom: "noix de muscade", obligatoire: false }
        ],
        ustensiles: ["plat à gratin", "four", "couteau"],
        tags: ["classique", "réconfort", "végétarien"],
        instructions: [
            "Frottez le plat à gratin avec une gousse d'ail.",
            "Épluchez et coupez les pommes de terre en fines rondelles.",
            "Mélangez le lait et la crème, salez, poivrez et ajoutez la muscade.",
            "Disposez les pommes de terre dans le plat et versez le mélange.",
            "Enfournez à 150°C pendant au moins 1h15 pour que ce soit bien fondant."
        ]
    },
    {
        id: 6,
        titre: "Soupe à l'Oignon Gratinée",
        description: "Le réconfort ultime des nuits d'hiver.",
        temps: 45,
        difficulte: "Facile",
        emoji: "🥣",
        ingredients: [
            { nom: "oignons jaunes", obligatoire: true },
            { nom: "bouillon de bœuf", obligatoire: true },
            { nom: "pain baguette", obligatoire: true },
            { nom: "fromage râpé (gruyère)", obligatoire: true },
            { nom: "beurre", obligatoire: true }
        ],
        ustensiles: ["marmite", "four"],
        tags: ["hiver", "fête", "classique"],
        instructions: [
            "Faites caraméliser les oignons émincés dans le beurre jusqu'à ce qu'ils soient bruns.",
            "Versez le bouillon de bœuf et laissez mijoter 20 minutes.",
            "Disposez la soupe dans des bols allant au four.",
            "Ajoutez une tranche de pain grillé et recouvrez généreusement de fromage.",
            "Passez sous le grill du four jusqu'à ce que ce soit bien doré."
        ]
    },
    {
        id: 7,
        titre: "Salade Niçoise authentique",
        description: "Fraîche, colorée et pleine des saveurs du sud.",
        temps: 25,
        difficulte: "Très facile",
        emoji: "🥗",
        ingredients: [
            { nom: "thon en boîte", obligatoire: true },
            { nom: "oeufs", obligatoire: true },
            { nom: "tomates", obligatoire: true },
            { nom: "haricots verts (cuits)", obligatoire: true },
            { nom: "olives noires", obligatoire: false },
            { nom: "anchois", obligatoire: false }
        ],
        ustensiles: ["saladier", "couteau"],
        tags: ["frais", "santé", "été"],
        instructions: [
            "Faites cuire les haricots verts à la vapeur et les oeufs (9 min).",
            "Mélangez la salade avec les tomates, le thon et les haricots.",
            "Ajoutez les quartiers d'oeufs durs, les olives et les anchois.",
            "Assaisonnez d'une vinaigrette simple à l'huile d'olive."
        ]
    },
    {
        id: 8,
        titre: "Tartare de Boeuf au couteau",
        description: "La viande préparée avec amour, relevée de condiments.",
        temps: 20,
        difficulte: "Moyen",
        emoji: "🥩",
        ingredients: [
            { nom: "viande hachée de qualité", obligatoire: true },
            { nom: "jaune d'œuf", obligatoire: true },
            { nom: "câpres", obligatoire: true },
            { nom: "oignon rouge", obligatoire: true },
            { nom: "moutarde", obligatoire: true },
            { nom: "sauce worcestershire", obligatoire: false }
        ],
        ustensiles: ["couteau bien aiguisé", "bol"],
        tags: ["bistrot", "viande"],
        instructions: [
            "Taillez la viande en tout petits dés au couteau.",
            "Mélangez le jaune d'oeuf, la moutarde, les câpres et l'oignon haché.",
            "Incorporez la viande à la préparation.",
            "Salez, poivrez et servez immédiatement avec des frites."
        ]
    },
    {
        id: 9,
        titre: "Magret de Canard au Miel",
        description: "Une cuisson rosée et un glaçage sucré-salé irrésistible.",
        temps: 25,
        difficulte: "Moyen",
        emoji: "🦆",
        ingredients: [
            { nom: "magret de canard", obligatoire: true },
            { nom: "miel", obligatoire: true },
            { nom: "vinaigre balsamique", obligatoire: true },
            { nom: "sel", obligatoire: true },
            { nom: "poivre", obligatoire: true }
        ],
        ustensiles: ["poêle", "couteau"],
        tags: ["fête", "gastronomique"],
        instructions: [
            "Quadrillez la peau du magret avec un couteau sans toucher la chair.",
            "Démarrez la cuisson côté peau à feu moyen pendant 8 minutes.",
            "Retirez l'excédent de gras et faites cuire 3 minutes côté chair.",
            "Réservez la viande dans du papier alu.",
            "Déglacez la poêle avec le miel et le vinaigre pour créer la sauce.",
            "Tranchez le magret et nappez de sauce avant de servir."
        ]
    },
    {
        id: 10,
        titre: "Salade César Royale",
        description: "La légende des salades : poulet croustillant, sauce onctueuse et parmesan.",
        temps: 30,
        difficulte: "Facile",
        emoji: "🥗",
        ingredients: [
            { nom: "salade romaine", obligatoire: true },
            { nom: "filet de poulet", obligatoire: true },
            { nom: "parmesan", obligatoire: true },
            { nom: "pain", obligatoire: true },
            { nom: "sauce césar (en pot ou maison)", obligatoire: true }
        ],
        ustensiles: ["poêle", "saladier"],
        tags: ["salade", "frais", "complet"],
        instructions: [
            "Faites dorer le poulet coupé en lanières à la poêle.",
            "Coupez le pain en dés et faites-en des croûtons à la poêle avec un peu d'huile.",
            "Mélangez la salade, le poulet et les croûtons dans un saladier.",
            "Ajoutez des copeaux de parmesan.",
            "Arrosez généreusement de sauce et mélangez le tout."
        ]
    },
    {
        id: 11,
        titre: "Lasagnes à la Bolognaise",
        description: "Le plat italien gourmand par excellence.",
        temps: 60,
        difficulte: "Moyen",
        emoji: "🍝",
        ingredients: [
            { nom: "pâtes (lasagnes)", obligatoire: true },
            { nom: "viande hachée", obligatoire: true },
            { nom: "tomates", obligatoire: true },
            { nom: "fromage râpé", obligatoire: true },
            { nom: "beurre", obligatoire: true },
            { nom: "farine", obligatoire: true },
            { nom: "lait", obligatoire: true }
        ],
        ustensiles: ["plat à gratin", "four"],
        tags: ["italien", "familial"],
        instructions: [
            "Préparez une sauce bolognaise avec la viande et la tomate.",
            "Préparez une béchamel avec le beurre, la farine et le lait.",
            "Alternez couches de pâtes, bolognaise et béchamel.",
            "Finissez par une couche de fromage.",
            "Faites cuire 35 minutes à 180°C."
        ]
    },
    {
        id: 12,
        titre: "Risotto aux Champignons",
        description: "Crémeux, fondant et délicieusement boisé.",
        temps: 35,
        difficulte: "Difficile",
        emoji: "🍚",
        ingredients: [
            { nom: "riz", obligatoire: true },
            { nom: "champignons", obligatoire: true },
            { nom: "parmesan", obligatoire: true },
            { nom: "oignons", obligatoire: true },
            { nom: "bouillon", obligatoire: true }
        ],
        ustensiles: ["casserole"],
        tags: ["végétarien", "gastronomique"],
        instructions: [
            "Faites revenir les oignons et les champignons.",
            "Ajoutez le riz et faites-le nacrer.",
            "Ajoutez le bouillon louche après louche en remuant sans cesse.",
            "Ajoutez le parmesan à la fin pour la texture."
        ]
    },
    {
        id: 13,
        titre: "Spaghetti Carbonara (Vraie)",
        description: "Pas de crème ! Juste des œufs, du pecorino et du guanciale (ou pancetta).",
        temps: 20,
        difficulte: "Facile",
        emoji: "🍝",
        ingredients: [
            { nom: "pâtes", obligatoire: true },
            { nom: "pancetta ou lardons", obligatoire: true },
            { nom: "oeufs", obligatoire: true },
            { nom: "parmesan ou pecorino", obligatoire: true }
        ],
        ustensiles: ["casserole", "poêle"],
        tags: ["italien", "rapide"],
        instructions: [
            "Cuisez les pâtes dans l'eau bouillante.",
            "Faites dorer la pancetta à la poêle.",
            "Battez les oeufs avec le fromage.",
            "Mélangez les pâtes égouttées avec la pancetta.",
            "Hors du feu, versez le mélange d'oeufs et remuez vite pour créer la sauce crémeuse."
        ]
    },
    {
        id: 14,
        titre: "Tartiflette au Reblochon",
        description: "La reine des pistes ! Pommes de terre, lardons, oignons et reblochon coulant.",
        temps: 45,
        difficulte: "Moyen",
        emoji: "🥘",
        ingredients: [
            { nom: "pommes de terre", obligatoire: true },
            { nom: "reblochon", obligatoire: true },
            { nom: "lardons", obligatoire: true },
            { nom: "oignons", obligatoire: true },
            { nom: "vin blanc", obligatoire: false }
        ],
        ustensiles: ["plat à gratin", "four", "poêle"],
        tags: ["hiver", "montagne", "familial"],
        instructions: [
            "Cuisez les pommes de terre à l'eau.",
            "Faites revenir lardons et oignons à la poêle.",
            "Coupez les pommes de terre en rondelles et disposez-les dans le plat.",
            "Ajoutez lardons et oignons, puis un petit fond de vin blanc.",
            "Coupez le reblochon en deux dans l'épaisseur et posez-le sur le dessus.",
            "Faites gratiner au four 20 minutes à 200°C."
        ]
    },
    {
        id: 15,
        titre: "Hachis Parmentier",
        description: "Le confort d'une purée maison et d'une viande savoureuse.",
        temps: 45,
        difficulte: "Facile",
        emoji: "🥘",
        ingredients: [
            { nom: "pommes de terre", obligatoire: true },
            { nom: "viande hachée", obligatoire: true },
            { nom: "beurre", obligatoire: true },
            { nom: "lait", obligatoire: true },
            { nom: "oignons", obligatoire: true },
            { nom: "fromage râpé", obligatoire: false }
        ],
        ustensiles: ["plat à gratin", "four", "presse-purée"],
        tags: ["familial", "budget"],
        instructions: [
            "Cuisez les pommes de terre à l'eau et écrasez-les en purée avec beurre et lait.",
            "Faites revenir la viande avec les oignons émincés.",
            "Disposez la viande au fond du plat à gratin.",
            "Recouvrez avec la purée et striez avec une fourchette.",
            "Ajoutez du fromage si désiré et gratinez 15 minutes au four."
        ]
    },
    {
        id: 16,
        titre: "Pot-au-Feu",
        description: "Le bouillon fumant et les viandes tendres du dimanche.",
        temps: 180,
        difficulte: "Moyen",
        emoji: "🍲",
        ingredients: [
            { nom: "boeuf", obligatoire: true },
            { nom: "plats-de-côtes", obligatoire: true },
            { nom: "poireau", obligatoire: true },
            { nom: "carottes", obligatoire: true },
            { nom: "navets", obligatoire: true },
            { nom: "os à moelle", obligatoire: false }
        ],
        ustensiles: ["marmite"],
        tags: ["mijote", "hiver"],
        instructions: [
            "Mettez la viande dans une grande marmite d'eau froide et portez à ébullition.",
            "Écumez soigneusement les impuretés en surface.",
            "Ajoutez les légumes lavés et coupés en gros morceaux.",
            "Laissez mijoter à petits bouillons pendant 3 heures.",
            "Servez le bouillon en entrée et la viande/légumes avec du gros sel."
        ]
    },
    {
        id: 17,
        titre: "Cassoulet de Castelnaudary",
        description: "Le plat languedocien par excellence, riche et généreux.",
        temps: 240,
        difficulte: "Difficile",
        emoji: "🍲",
        ingredients: [
            { nom: "haricots blancs", obligatoire: true },
            { nom: "confit de canard", obligatoire: true },
            { nom: "saucisse de toulouse", obligatoire: true },
            { nom: "lardons", obligatoire: true },
            { nom: "couenne de porc", obligatoire: false },
            { nom: "ail", obligatoire: true }
        ],
        ustensiles: ["cassole", "cocotte"],
        tags: ["traditionnel", "mijote", "fête"],
        instructions: [
            "Faites tremper les haricots la veille.",
            "Cuisez les haricots à l'eau avec la couenne pendant 1h30.",
            "Dans une cocotte, faites dorer les saucisses et le canard.",
            "Disposez les haricots et les viandes dans une cassole en terre cuite.",
            "Ajoutez du bouillon de cuisson des haricots.",
            "Enfournez à 150°C pendant 2h en 'cassant la croûte' qui se forme 7 fois."
        ]
    },
    {
        id: 18,
        titre: "Crème Brûlée à la Vanille",
        description: "L'onctuosité protégée par une fine couche de caramel craquant.",
        temps: 60,
        difficulte: "Moyen",
        emoji: "🍮",
        ingredients: [
            { nom: "jaune d'œuf", obligatoire: true },
            { nom: "crème fraîche liquide", obligatoire: true },
            { nom: "sucre", obligatoire: true },
            { nom: "vanille en poudre", obligatoire: true }
        ],
        ustensiles: ["ramequins", "four", "chalumeau"],
        tags: ["dessert", "classique"],
        instructions: [
            "Préchauffez le four à 100°C.",
            "Fouettez les jaunes d'oeufs avec le sucre jusqu'à ce que le mélange blanchisse.",
            "Ajoutez la crème et la vanille, mélangez doucement sans faire mousser.",
            "Répartissez dans les ramequins et cuisez au bain-marie pendant 50 minutes.",
            "Laissez refroidir et placez au réfrigérateur au moins 4 heures.",
            "Saupoudrez de sucre et caramélisez au chalumeau juste avant de servir."
        ]
    },
    {
        id: 19,
        titre: "Profiteroles au Chocolat",
        description: "Le dessert gourmand : choux, glace vanille et chocolat chaud.",
        temps: 45,
        difficulte: "Difficile",
        emoji: "🍦",
        ingredients: [
            { nom: "pâte à choux", obligatoire: true },
            { nom: "glace vanille", obligatoire: true },
            { nom: "chocolat noir", obligatoire: true },
            { nom: "beurre", obligatoire: true }
        ],
        ustensiles: ["casserole", "four", "poche à douille"],
        tags: ["dessert", "gourmand"],
        instructions: [
            "Préparez les choux (ou utilisez des prêts à l'emploi).",
            "Coupez les choux en deux et garnissez-les d'une boule de glace vanille.",
            "Faites fondre le chocolat avec un peu de beurre et d'eau pour obtenir une sauce lisse.",
            "Disposez les choux dans une assiette et nappez-les généreusement de sauce chocolat chaude.",
            "Servez immédiatement pour le contraste chaud-froid."
        ]
    },
    {
        id: 20,
        titre: "Steak Frites de Bistrot",
        description: "Le plaisir simple d'une viande de qualité et de frites maison.",
        temps: 30,
        difficulte: "Facile",
        emoji: "🥩",
        ingredients: [
            { nom: "boeuf (steak)", obligatoire: true },
            { nom: "pommes de terre", obligatoire: true },
            { nom: "huile", obligatoire: true },
            { nom: "sel", obligatoire: true }
        ],
        ustensiles: ["friteuse", "poêle", "air fryer"],
        tags: ["rapide", "bistrot"],
        instructions: [
            "Épluchez et coupez les pommes de terre en bâtonnets.",
            "Faites cuire les frites à la friteuse (deux bains) ou à l'Air Fryer (25 min à 200°C).",
            "Faites saisir le steak à la poêle à feu très vif selon votre goût (bleu, saignant, à point).",
            "Salez et poivrez la viande après cuisson.",
            "Servez bien chaud avec une pincée de sel sur les frites."
        ]
    },
    {
        id: 21,
        titre: "Gratin dauphinois traditionnel",
        description: "Une recette de gratin de pommes de terre à la crème et à l'ail.",
        temps: 60,
        difficulte: "Facile",
        emoji: "🥘",
        ingredients: [
            { nom: "pomme de terre", obligatoire: true },
            { nom: "crème liquide", obligatoire: true },
            { nom: "ail", obligatoire: true },
            { nom: "sel", obligatoire: true },
            { nom: "poivre", obligatoire: true }
        ],
        ustensiles: ["plat à gratin", "four"],
        tags: ["Gratin", "Pommes de terre", "Accompagnement"],
        instructions: [
            "Préchauffer le four à 150°C.",
            "Eplucher et couper les pommes de terres en rondelles.",
            "Presser l'ail.",
            "Napper le fond d'un plat à gratin de crème.",
            "Alterner une couche de pommes de terres, crème, ail, sel, poivre.",
            "Terminer en nappant de crème.",
            "Mettre au four pendant au moins une heure."
        ],
        image: "https://assets.afcdn.com/recipe/20201217/116564_w648h414c1cx1009cy951.webp"
    },
    {
        id: 22,
        titre: "Quiche lorraine maison",
        description: "La quiche traditionnelle à base de lardons, crème et oeufs.",
        temps: 55,
        difficulte: "Facile",
        emoji: "🥧",
        ingredients: [
            { nom: "pâte brisée", obligatoire: true },
            { nom: "lardons", obligatoire: true },
            { nom: "oeufs", obligatoire: true },
            { nom: "crème fraîche", obligatoire: true },
            { nom: "lait", obligatoire: true },
            { nom: "beurre", obligatoire: true },
            { nom: "muscade", obligatoire: true }
        ],
        ustensiles: ["moule à tarte", "four", "poêle"],
        tags: ["Quiche", "Plat principal", "Classique"],
        instructions: [
            "Préchauffer le four à 180°C.",
            "Etaler la pâte dans un moule, la piquer à la fourchette.",
            "Faire rissoler les lardons à la poêle.",
            "Battre les oeufs, la crème fraîche et le lait. Ajouter les lardons.",
            "Assaisonner de sel, poivre et muscade.",
            "Verser sur la pâte et cuire 45 à 50 min."
        ],
        image: "https://assets.afcdn.com/recipe/20161128/28118_w648h414c1cx845cy3505.webp"
    },
    {
        id: 23,
        titre: "Poulet rôti simple",
        description: "Un poulet rôti juteux et croustillant sans fioritures.",
        temps: 60,
        difficulte: "Facile",
        emoji: "🍗",
        ingredients: [
            { nom: "poulet", obligatoire: true },
            { nom: "huile", obligatoire: true }
        ],
        ustensiles: ["plat à four", "four"],
        tags: ["Poulet", "Plat principal", "Classique"],
        instructions: [
            "Préchauffer le four à 190°.",
            "Masser le poulet avec de l'huile.",
            "Le poser dans un plat et le mettre au four pendant 1 h 30.",
            "Ne pas le piquer ni le retourner pendant la cuisson."
        ],
        image: "https://assets.afcdn.com/recipe/20130909/63747_w648h414c1cx1872cy2808.webp"
    },
    {
        id: 24,
        titre: "Salade Niçoise authentique",
        description: "La véritable salade niçoise avec thon, anchois et légumes frais.",
        temps: 28,
        difficulte: "Facile",
        emoji: "🥗",
        ingredients: [
            { nom: "tomates", obligatoire: true },
            { nom: "poivron vert", obligatoire: true },
            { nom: "oeufs", obligatoire: true },
            { nom: "oignons cébettes", obligatoire: true },
            { nom: "févettes", obligatoire: true },
            { nom: "thon", obligatoire: true },
            { nom: "anchois", obligatoire: true },
            { nom: "olives noires", obligatoire: true },
            { nom: "basilic", obligatoire: true },
            { nom: "huile d'olive", obligatoire: true }
        ],
        ustensiles: ["saladier", "casserole"],
        tags: ["Salade", "Entrée", "Nicoise"],
        instructions: [
            "Faire durcir les oeufs, puis les faire refroidir.",
            "Disposer les légumes, le thon et les oeufs dans un plat.",
            "Ajouter les anchois, les olives et le basilic.",
            "Arroser d'huile d'olive et de vinaigre."
        ],
        image: "https://assets.afcdn.com/recipe/20190704/94687_w648h414c1cx3008cy2008.webp"
    },
    {
        id: 25,
        titre: "Mousse au chocolat facile",
        description: "Une mousse au chocolat aérienne préparée avec seulement 3 ingrédients.",
        temps: 15,
        difficulte: "Facile",
        emoji: "🍮",
        ingredients: [
            { nom: "chocolat noir", obligatoire: true },
            { nom: "oeufs", obligatoire: true },
            { nom: "sucre vanillé", obligatoire: true }
        ],
        ustensiles: ["bol", "fouet", "verrines"],
        tags: ["Dessert", "Chocolat", "Classique"],
        instructions: [
            "Séparer les blancs des jaunes d'oeufs.",
            "Faire fondre le chocolat au bain-marie.",
            "Incorporer les jaunes et le sucre au chocolat.",
            "Battre les blancs en neige ferme et les ajouter délicatement."
        ],
        image: "https://assets.afcdn.com/recipe/20210311/118509_w648h414c1cx300cy533.webp"
    },
    {
        id: 26,
        titre: "Pâte à crêpes raffinée",
        description: "Une pâte à crêpes lisse et parfumée pour des crêpes parfaites.",
        temps: 17,
        difficulte: "Facile",
        emoji: "🥞",
        ingredients: [
            { nom: "farine", obligatoire: true },
            { nom: "oeufs", obligatoire: true },
            { nom: "lait", obligatoire: true },
            { nom: "beurre", obligatoire: true },
            { nom: "sucre", obligatoire: true },
            { nom: "grand-marnier", obligatoire: false }
        ],
        ustensiles: ["saladier", "fouet", "poêle à crêpes"],
        tags: ["Crêpes", "Dessert", "Gouter"],
        instructions: [
            "Mélanger farine, sel et sucre. Faire une fontaine.",
            "Ajouter les oeufs, puis le beurre fondu.",
            "Incorporer le lait petit à petit pour éviter les grumeaux.",
            "Cuire dans une poêle chaude huilée."
        ],
        image: "https://assets.afcdn.com/recipe/20260126/165572_w648h414c1cx3210cy2530.webp"
    },
    {
        id: 27,
        titre: "Lasagnes à la bolognaise",
        description: "Lasagnes généreuses avec sauce bolognaise maison et béchamel.",
        temps: 120,
        difficulte: "Moyen",
        emoji: "🍝",
        ingredients: [
            { nom: "lasagnes", obligatoire: true },
            { nom: "boeuf haché", obligatoire: true },
            { nom: "purée de tomate", obligatoire: true },
            { nom: "lait", obligatoire: true },
            { nom: "farine", obligatoire: true },
            { nom: "beurre", obligatoire: true },
            { nom: "parmesan", obligatoire: true }
        ],
        ustensiles: ["plat à gratin", "four", "casserole"],
        tags: ["Lasagnes", "Plat principal", "Italien"],
        instructions: [
            "Préparer la sauce bolognaise et la béchamel.",
            "Alterner les couches de lasagnes, bolognaise et béchamel.",
            "Terminer par du fromage et cuire 25 minutes à 200°C."
        ],
        image: "https://assets.afcdn.com/recipe/20200408/109520_w648h414c1cx1866cy2800.webp"
    },
    {
        id: 28,
        titre: "Cake à la banane",
        description: "Un gâteau moelleux pour utiliser vos bananes trop mûres.",
        temps: 55,
        difficulte: "Facile",
        emoji: "🍞",
        ingredients: [
            { nom: "bananes", obligatoire: true },
            { nom: "farine", obligatoire: true },
            { nom: "sucre", obligatoire: true },
            { nom: "beurre", obligatoire: true },
            { nom: "oeuf", obligatoire: true },
            { nom: "levure chimique", obligatoire: true }
        ],
        ustensiles: ["moule à cake", "four", "bol"],
        tags: ["Cake", "Banane", "Gouter"],
        instructions: [
            "Mélanger les ingrédients secs.",
            "Mélanger sucre, oeuf, beurre et bananes écrasées.",
            "Réunir les deux préparations.",
            "Cuire 45 min à 180°C."
        ],
        image: "https://assets.afcdn.com/recipe/20181017/82817_w648h414c1cx1866cy2488.webp"
    },
    {
        id: 29,
        titre: "Boeuf Bourguignon express",
        description: "Une version rapide à la cocotte-minute du célèbre plat bourguignon.",
        temps: 60,
        difficulte: "Moyen",
        emoji: "🍲",
        ingredients: [
            { nom: "boeuf", obligatoire: true },
            { nom: "lardons", obligatoire: true },
            { nom: "vin rouge", obligatoire: true },
            { nom: "oignons", obligatoire: true },
            { nom: "champignons de Paris", obligatoire: true },
            { nom: "farine", obligatoire: true }
        ],
        ustensiles: ["cocotte-minute"],
        tags: ["Boeuf", "Plat principal", "Classique"],
        instructions: [
            "Faire roussir la viande et les lardons.",
            "Ajouter oignons, champignons et farine.",
            "Mouiller au vin rouge.",
            "Cuire 60 min sous pression."
        ],
        image: "https://assets.afcdn.com/recipe/20131009/56293_w648h414c1cx1872cy2808.webp"
    },
    {
        id: 30,
        titre: "Gâteau au yaourt",
        description: "Le gâteau d'enfance par excellence, simple et inratable.",
        temps: 45,
        difficulte: "Facile",
        emoji: "🍰",
        ingredients: [
            { nom: "yaourt nature", obligatoire: true },
            { nom: "farine", obligatoire: true },
            { nom: "sucre", obligatoire: true },
            { nom: "oeufs", obligatoire: true },
            { nom: "levure chimique", obligatoire: true },
            { nom: "huile", obligatoire: true }
        ],
        ustensiles: ["moule à gâteau", "four", "saladier"],
        tags: ["Gateau", "Yaourt", "Dessert"],
        instructions: [
            "Mélanger le yaourt avec la levure.",
            "Ajouter huile, sucre, farine et oeufs.",
            "Verser dans un moule beurré.",
            "Enfourner 30 minutes à 180°C."
        ],
        image: "https://assets.afcdn.com/recipe/20200828/113345_w648h414c1cx2841cy1816.webp"
    },
    {
        id: 31,
        titre: "Butternut farcies au quinoa",
        description: "Un plat complet sain composé de courges butternut farcies au quinoa et pois chiches.",
        temps: 70,
        difficulte: "Facile",
        emoji: "🎃",
        ingredients: [
            { nom: "Courge butternut", obligatoire: true },
            { nom: "Quinoa", obligatoire: true },
            { nom: "Pois chiches", obligatoire: true },
            { nom: "Persil", obligatoire: true },
            { nom: "Huile d'olive", obligatoire: true }
        ],
        ustensiles: ["four", "couteau", "saladier"],
        tags: ["santé", "équilibre", "plat complet", "légumes"],
        instructions: [
            "Préchauffez le four à 200°C.",
            "Coupez les butternuts en 2 et évidez-les.",
            "Mélangez le quinoa, pois chiches, persil et huile.",
            "Remplissez les butternuts et enfournez 50 minutes."
        ],
        image: "https://www.mangerbouger.fr/manger-mieux/la-fabrique-a-menus/_next/image?url=https%3A%2F%2Fapi-prod-fam.mangerbouger.fr%2Fstorage%2Frecettes%2FButternut-farcies-quinoa-pois-chiches.jpg&w=3840&q=75"
    },
    {
        id: 32,
        titre: "Quiche poireaux-roquefort",
        description: "Une quiche savoureuse aux poireaux et au roquefort.",
        temps: 45,
        difficulte: "Facile",
        emoji: "🥧",
        ingredients: [
            { nom: "Poireau", obligatoire: true },
            { nom: "Pâte feuilletée", obligatoire: true },
            { nom: "Crème fraîche", obligatoire: true },
            { nom: "Roquefort", obligatoire: true },
            { nom: "Œufs", obligatoire: true }
        ],
        ustensiles: ["moule", "four", "poêle"],
        tags: ["santé", "équilibre", "plat complet", "végétarien"],
        instructions: [
            "Cuire les poireaux à la poêle pendant 20 min.",
            "Étaler la pâte dans un moule et pré-cuire 10 min.",
            "Battre les œufs avec la crème et le roquefort.",
            "Verser sur les poireaux et enfourner 25 min."
        ],
        image: "https://www.mangerbouger.fr/manger-mieux/la-fabrique-a-menus/_next/image?url=https%3A%2F%2Fapi-prod-fam.mangerbouger.fr%2Fstorage%2Frecettes%2FQuiche-poireaux-roquefort.jpg&w=3840&q=75"
    },
    {
        id: 33,
        titre: "Gratin de chou-fleur léger",
        description: "Un gratin de chou-fleur fondant avec une sauce béchamel légère.",
        temps: 45,
        difficulte: "Facile",
        emoji: "🥦",
        ingredients: [
            { nom: "Chou-fleur", obligatoire: true },
            { nom: "Lait demi-écrémé", obligatoire: true },
            { nom: "Emmental râpé", obligatoire: true },
            { nom: "Farine", obligatoire: true },
            { nom: "Beurre", obligatoire: true }
        ],
        ustensiles: ["casserole", "plat à gratin", "cuiseur vapeur"],
        tags: ["santé", "équilibre", "plat complet", "légumes"],
        instructions: [
            "Cuire le chou-fleur à la vapeur 20 min.",
            "Préparer une béchamel légère.",
            "Placer le chou-fleur dans un plat, verser la sauce.",
            "Parsemer de fromage et faire gratiner au four."
        ],
        image: "https://www.mangerbouger.fr/manger-mieux/la-fabrique-a-menus/_next/image?url=https%3A%2F%2Fapi-prod-fam.mangerbouger.fr%2Fstorage%2Frecettes%2FGratin-de-chou-fleur.jpg&w=3840&q=75"
    },
    {
        id: 34,
        titre: "Purée à l'huile d'olive",
        description: "Une purée onctueuse revisitée avec de l'huile d'olive.",
        temps: 35,
        difficulte: "Facile",
        emoji: "🥔",
        ingredients: [
            { nom: "Pomme de terre", obligatoire: true },
            { nom: "Lait demi-écrémé", obligatoire: true },
            { nom: "Huile d'olive", obligatoire: true },
            { nom: "Noix de muscade", obligatoire: true }
        ],
        ustensiles: ["moulin à légumes", "casserole"],
        tags: ["santé", "équilibre", "accompagnement", "végétarien"],
        instructions: [
            "Cuire les pommes de terre à l'eau.",
            "Passer au moulin en ajoutant le lait chaud.",
            "Ajouter l'huile d'olive et la muscade. Mélanger."
        ],
        image: "https://www.mangerbouger.fr/manger-mieux/la-fabrique-a-menus/_next/image?url=https%3A%2F%2Fapi-prod-fam.mangerbouger.fr%2Fstorage%2Frecettes%2FPuree-de-pommes-de-terre-a-lhuile-dolive.jpg&w=3840&q=75"
    },
    {
        id: 35,
        titre: "Gâteau bananes et noix",
        description: "Un gâteau énergétique aux bananes et aux éclats de noix.",
        temps: 50,
        difficulte: "Facile",
        emoji: "🍰",
        ingredients: [
            { nom: "Bananes", obligatoire: true },
            { nom: "Noix", obligatoire: true },
            { nom: "Farine", obligatoire: true },
            { nom: "Sucre", obligatoire: true },
            { nom: "Beurre", obligatoire: true },
            { nom: "Œufs", obligatoire: true }
        ],
        ustensiles: ["moule", "saladier", "four"],
        tags: ["santé", "équilibre", "dessert", "fruits"],
        instructions: [
            "Mélanger beurre fondu et sucre. Ajouter les œufs.",
            "Incorporer bananes écrasées, noix et farine.",
            "Cuire 45 min à 180°C."
        ],
        image: "https://www.mangerbouger.fr/manger-mieux/la-fabrique-a-menus/_next/image?url=https%3A%2F%2Fapi-prod-fam.mangerbouger.fr%2Fstorage%2Frecettes%2FGateau-aux-bananes-et-aux-noix.jpg&w=3840&q=75"
    },
    {
        id: 36,
        titre: "Gratin épinards et saumon",
        description: "Une alliance classique et saine entre saumon et épinards.",
        temps: 55,
        difficulte: "Facile",
        emoji: "🐟",
        ingredients: [
            { nom: "Épinards", obligatoire: true },
            { nom: "Pavé de saumon", obligatoire: true },
            { nom: "Fromage de chèvre", obligatoire: true }
        ],
        ustensiles: ["plat à gratin", "four"],
        tags: ["santé", "équilibre", "plat complet", "poisson"],
        instructions: [
            "Cuire les épinards et les égoutter.",
            "Mélanger le chèvre aux épinards.",
            "Disposer saumon et épinards dans un plat.",
            "Enfourner 20 minutes."
        ],
        image: "https://www.mangerbouger.fr/manger-mieux/la-fabrique-a-menus/_next/image?url=https%3A%2F%2Fapi-prod-fam.mangerbouger.fr%2Fstorage%2Frecettes%2FGratin-epinards-saumon.jpg&w=3840&q=75"
    },
    {
        id: 37,
        titre: "Steaks sauce au poivre",
        description: "Un plat express de viande rouge avec une sauce onctueuse.",
        temps: 15,
        difficulte: "Facile",
        emoji: "🥩",
        ingredients: [
            { nom: "Steak", obligatoire: true },
            { nom: "Crème fraîche", obligatoire: true },
            { nom: "Moutarde", obligatoire: true },
            { nom: "Poivre", obligatoire: true }
        ],
        ustensiles: ["poêle"],
        tags: ["santé", "équilibre", "express", "protéines"],
        instructions: [
            "Chauffer crème, moutarde et poivre en sauce.",
            "Saisir la viande 2 min de chaque côté.",
            "Napper de sauce et servir."
        ],
        image: "https://www.mangerbouger.fr/manger-mieux/la-fabrique-a-menus/_next/image?url=https%3A%2F%2Fapi-prod-fam.mangerbouger.fr%2Fstorage%2Frecettes%2FSteaks-sauce-au-poivre.jpg&w=3840&q=75"
    },
    {
        id: 38,
        titre: "Boulettes de bœuf aux herbes",
        description: "Des boulettes maison riches en herbes fraîches.",
        temps: 20,
        difficulte: "Facile",
        emoji: "🧆",
        ingredients: [
            { nom: "Steak haché", obligatoire: true },
            { nom: "Persil", obligatoire: true },
            { nom: "Coriandre", obligatoire: true },
            { nom: "Œuf", obligatoire: true }
        ],
        ustensiles: ["saladier", "poêle"],
        tags: ["santé", "équilibre", "protéines", "fait maison"],
        instructions: [
            "Mélanger viande, œuf et herbes ciselées.",
            "Former des boulettes et fariner.",
            "Faire dorer dans l'huile 10 min."
        ],
        image: "https://www.mangerbouger.fr/manger-mieux/la-fabrique-a-menus/_next/image?url=https%3A%2F%2Fapi-prod-fam.mangerbouger.fr%2Fstorage%2Frecettes%2FBoulettes-de-boeuf-aux-herbes.jpg&w=3840&q=75"
    },
    {
        id: 39,
        titre: "Petits légumes croquants",
        description: "Une salade fraîche de carottes et courgettes râpées.",
        temps: 15,
        difficulte: "Facile",
        emoji: "🥗",
        ingredients: [
            { nom: "Carotte", obligatoire: true },
            { nom: "Courgettes", obligatoire: true },
            { nom: "Pignons de pin", obligatoire: true }
        ],
        ustensiles: ["râpe", "saladier", "poêle"],
        tags: ["santé", "équilibre", "légumes", "express"],
        instructions: [
            "Râper les carottes et courgettes.",
            "Griller les pignons à la poêle.",
            "Mélanger le tout avec une vinaigrette."
        ],
        image: "https://www.mangerbouger.fr/manger-mieux/la-fabrique-a-menus/_next/image?url=https%3A%2F%2Fapi-prod-fam.mangerbouger.fr%2Fstorage%2Frecettes%2FPetits-legumes-croquants.jpg&w=3840&q=75"
    },
    {
        id: 40,
        titre: "Trifles à la mangue",
        description: "Un dessert frais mêlant mangue et fromage blanc.",
        temps: 70,
        difficulte: "Facile",
        emoji: "🍧",
        ingredients: [
            { nom: "Mangue", obligatoire: true },
            { nom: "Fromage blanc", obligatoire: true },
            { nom: "Mascarpone", obligatoire: true },
            { nom: "Citron", obligatoire: true }
        ],
        ustensiles: ["verrines", "saladier"],
        tags: ["santé", "équilibre", "dessert", "fruits"],
        instructions: [
            "Couper la mangue en dés.",
            "Fouetter fromage blanc, mascarpone et sucre.",
            "Alterner couches de mangue et crème en verrines.",
            "Placer au frais 1h."
        ],
        image: "https://www.mangerbouger.fr/manger-mieux/la-fabrique-a-menus/_next/image?url=https%3A%2F%2Fapi-prod-fam.mangerbouger.fr%2Fstorage%2Frecettes%2FTrifles-a-la-mangue.jpg&w=3840&q=75"
    },
    {
        id: 41,
        titre: "Framboisier léger",
        description: "Un gâteau fruité avec mousse légère et génoise fondante.",
        temps: 50,
        difficulte: "Moyen",
        emoji: "🍰",
        ingredients: [
            { nom: "Framboises", obligatoire: true },
            { nom: "Fromage blanc", obligatoire: true },
            { nom: "Farine", obligatoire: true },
            { nom: "Oeufs", obligatoire: true },
            { nom: "Sucre", obligatoire: true }
        ],
        ustensiles: ["Moule à manqué", "Fouet électrique"],
        tags: ["Dessert", "Gâteaux", "Framboise"],
        instructions: [
            "Préparer la génoise et cuire 20 min à 180°C.",
            "Préparer la mousse au fromage blanc et framboises.",
            "Monter le gâteau et réserver au frais 6h."
        ],
        image: "https://img.cuisineactuelle.fr/1200x675/2018/09/25/i47606-framboisier.jpg"
    },
    {
        id: 42,
        titre: "Bottereaux vendéens",
        description: "Beignets traditionnels parfaits pour le goûter.",
        temps: 35,
        difficulte: "Facile",
        emoji: "🍩",
        ingredients: [
            { nom: "Farine", obligatoire: true },
            { nom: "Sucre", obligatoire: true },
            { nom: "Oeufs", obligatoire: true },
            { nom: "Beurre", obligatoire: true },
            { nom: "Huile de friture", obligatoire: true }
        ],
        ustensiles: ["Saladier", "Rouleau à pâtisserie", "Friteuse"],
        tags: ["Beignets", "Goûter", "Tradition"],
        instructions: [
            "Former une pâte avec farine, sucre, oeufs et beurre.",
            "Laisser reposer 2 heures.",
            "Étaler, découper en losanges et frire."
        ],
        image: "https://img.cuisineactuelle.fr/1200x675/2019/04/25/i54858-bottereaux.jpg"
    },
    {
        id: 43,
        titre: "Tchoutchouka",
        description: "Plat maghrébin aux poivrons, tomates et œufs.",
        temps: 46,
        difficulte: "Facile",
        emoji: "🥘",
        ingredients: [
            { nom: "Poivrons", obligatoire: true },
            { nom: "Tomates", obligatoire: true },
            { nom: "Oeufs", obligatoire: true },
            { nom: "Ail", obligatoire: true },
            { nom: "Huile d'olive", obligatoire: true }
        ],
        ustensiles: ["Grande poêle"],
        tags: ["Plat principal", "Cuisine du monde", "Végétarien"],
        instructions: [
            "Faire revenir poivrons et ail 15 min.",
            "Ajouter les tomates et mijoter 30 min.",
            "Casser les œufs dessus et cuire 8 min."
        ],
        image: "https://img.cuisineactuelle.fr/1200x675/2019/06/27/i21578-tchoutchouka.jpg"
    },
    {
        id: 44,
        titre: "Scones express",
        description: "Petits pains anglais parfaits pour le brunch.",
        temps: 25,
        difficulte: "Facile",
        emoji: "🥯",
        ingredients: [
            { nom: "Farine", obligatoire: true },
            { nom: "Beurre", obligatoire: true },
            { nom: "Lait", obligatoire: true },
            { nom: "Oeuf", obligatoire: true }
        ],
        ustensiles: ["Emporte-pièce", "Plaque de cuisson"],
        tags: ["Petit-déjeuner", "Brunch", "Rapide"],
        instructions: [
            "Mélanger farine, levure et beurre.",
            "Ajouter oeuf et lait.",
            "Découper à l'emporte-pièce et cuire 10 min à 210°C."
        ],
        image: "https://img.cuisineactuelle.fr/1200x675/2018/09/25/i41855-scones-rapides.jpg"
    },
    {
        id: 45,
        titre: "Sauce chocolat liquide",
        description: "Sauce onctueuse pour napper vos desserts.",
        temps: 20,
        difficulte: "Facile",
        emoji: "🍫",
        ingredients: [
            { nom: "Chocolat noir", obligatoire: true },
            { nom: "Lait", obligatoire: true }
        ],
        ustensiles: ["Casserole"],
        tags: ["Sauce", "Chocolat", "Accompagnement"],
        instructions: [
            "Casser le chocolat en morceaux.",
            "Faire fondre avec le lait au bain-marie.",
            "Remuer jusqu'à ce que ce soit lisse."
        ],
        image: "https://img.cuisineactuelle.fr/1200x675/2018/09/25/i55580-chocolat-liquide.jpg"
    },
    {
        id: 46,
        titre: "Pâté breton traditionnel",
        description: "Une terrine de campagne riche en saveurs.",
        temps: 108,
        difficulte: "Facile",
        emoji: "🥩",
        ingredients: [
            { nom: "Porc (gorge, épaule)", obligatoire: true },
            { nom: "Foie de porc", obligatoire: true },
            { nom: "Oignons", obligatoire: true },
            { nom: "Persil", obligatoire: true }
        ],
        ustensiles: ["Hachoir à viande", "Terrine"],
        tags: ["Entrée", "Charcuterie", "Terroir"],
        instructions: [
            "Hacher finement toutes les viandes.",
            "Mélanger avec oignons et persil.",
            "Cuire en terrine au four pendant 1h30."
        ],
        image: "https://img.cuisineactuelle.fr/1200x675/2021/06/02/i30579-pate-breton.jpg"
    },
    {
        id: 47,
        titre: "Gaufres croustillantes",
        description: "Recette pour des gaufres légères et croustillantes.",
        temps: 30,
        difficulte: "Facile",
        emoji: " waffle",
        ingredients: [
            { nom: "Farine", obligatoire: true },
            { nom: "Oeufs", obligatoire: true },
            { nom: "Lait", obligatoire: true },
            { nom: "Sucre", obligatoire: true }
        ],
        ustensiles: ["Saladier", "Gaufrier"],
        tags: ["Goûter", "Dessert", "Enfants"],
        instructions: [
            "Mélanger les ingrédients secs.",
            "Ajouter oeufs et lait en fouettant.",
            "Cuire dans un gaufrier chaud."
        ],
        image: "https://img.cuisineactuelle.fr/1200x675/2021/12/21/i39469-gaufre-croustillante.jpg"
    },
    {
        id: 48,
        titre: "Punch à la vanille",
        description: "Cocktail exotique parfumé à la vanille.",
        temps: 20,
        difficulte: "Facile",
        emoji: "🍹",
        ingredients: [
            { nom: "Rhum blanc", obligatoire: true },
            { nom: "Jus de fruits", obligatoire: true },
            { nom: "Vanille", obligatoire: true },
            { nom: "Sirop de sucre", obligatoire: true }
        ],
        ustensiles: ["Grand saladier"],
        tags: ["Boisson", "Cocktail", "Exotique"],
        instructions: [
            "Mélanger rhum, jus et sirop.",
            "Ajouter la vanille fendue.",
            "Mettre au frais 1h avant de servir."
        ],
        image: "https://img.cuisineactuelle.fr/1200x675/2018/09/25/i10872-punch-vanille.jpg"
    },
    {
        id: 49,
        titre: "Endives façon apéro",
        description: "Barquettes d'endives au bleu et noix.",
        temps: 20,
        difficulte: "Facile",
        emoji: "🥗",
        ingredients: [
            { nom: "Endives", obligatoire: true },
            { nom: "Bleu d'Auvergne", obligatoire: true },
            { nom: "Pommes", obligatoire: true },
            { nom: "Noix", obligatoire: true }
        ],
        ustensiles: ["Plat de service"],
        tags: ["Apéritif", "Fromage", "Salade"],
        instructions: [
            "Laver les feuilles d'endives.",
            "Garnir de pomme, fromage et noix.",
            "Arroser d'un filet de vinaigrette."
        ],
        image: "https://img.cuisineactuelle.fr/1200x675/2018/09/25/i56747-endives-apero.jpg"
    },
    {
        id: 50,
        titre: "Soupe julienne",
        description: "Une soupe de légumes légère et réconfortante.",
        temps: 40,
        difficulte: "Facile",
        emoji: "🥣",
        ingredients: [
            { nom: "Carottes", obligatoire: true },
            { nom: "Pommes de terre", obligatoire: true },
            { nom: "Poireau", obligatoire: true },
            { nom: "Beurre", obligatoire: true }
        ],
        ustensiles: ["Marmite", "Couteau"],
        tags: ["Soupe", "Légumes", "Sain"],
        instructions: [
            "Éplucher et émincer les légumes.",
            "Faire suer dans le beurre.",
            "Couvrir d'eau et cuire 20 min."
        ],
        image: "https://img.cuisineactuelle.fr/1200x675/2018/09/25/i51306-soupe-julienne.jpg"
    }
];

var commonIngredients = [
    // Légumes & Plantes
    { nom: "ail", emoji: "🧄" },
    { nom: "ail des ours", emoji: "🌿" },
    { nom: "amarante (feuilles)", emoji: "🌿" },
    { nom: "artichaut", emoji: "🥗" },
    { nom: "asperge blanche", emoji: "🥗" },
    { nom: "asperge verte", emoji: "🥗" },
    { nom: "aubergine", emoji: "🍆" },
    { nom: "aubergine blanche", emoji: "🍆" },
    { nom: "baselle", emoji: "🌿" },
    { nom: "betterave rouge", emoji: "🍠" },
    { nom: "betterave chioggia", emoji: "🍠" },
    { nom: "betterave jaune", emoji: "🍠" },
    { nom: "blette (bette à carde)", emoji: "🌿" },
    { nom: "brocoli", emoji: "🥦" },
    { nom: "brocoli à jets", emoji: "🥦" },
    { nom: "butternut (doubeurre)", emoji: "🎃" },
    { nom: "calebasse", emoji: "🥒" },
    { nom: "capucine tubéreuse", emoji: "🍠" },
    { nom: "cardon", emoji: "🌿" },
    { nom: "carotte", emoji: "🥕" },
    { nom: "carotte violette", emoji: "🥕" },
    { nom: "cébette", emoji: "🧅" },
    { nom: "céleri-branche", emoji: "🌿" },
    { nom: "céleri-rave", emoji: "🍠" },
    { nom: "cerfeuil tubéreux", emoji: "🍠" },
    { nom: "chayotte (christophine)", emoji: "🍐" },
    { nom: "chervis", emoji: "🍠" },
    { nom: "chicorée", emoji: "🥬" },
    { nom: "chou blanc", emoji: "🥬" },
    { nom: "chou cabus", emoji: "🥬" },
    { nom: "chou chinois (pak-choï)", emoji: "🥬" },
    { nom: "chou chinois (pétsaï)", emoji: "🥬" },
    { nom: "chou de bruxelles", emoji: "🥦" },
    { nom: "chou de milan", emoji: "🥬" },
    { nom: "chou-fleur", emoji: "🥦" },
    { nom: "chou frisé (kale)", emoji: "🥬" },
    { nom: "chou pointu", emoji: "🥬" },
    { nom: "chou rouge", emoji: "🥬" },
    { nom: "chou romanesco", emoji: "🥦" },
    { nom: "chou-rave", emoji: "🥬" },
    { nom: "ciboule", emoji: "🧅" },
    { nom: "ciboulette", emoji: "🌿" },
    { nom: "citrouille", emoji: "🎃" },
    { nom: "claytone de cuba", emoji: "🌿" },
    { nom: "concombre", emoji: "🥒" },
    { nom: "concombre arménien", emoji: "🥒" },
    { nom: "cornichon", emoji: "🥒" },
    { nom: "courge de nice", emoji: "🎃" },
    { nom: "courge gland", emoji: "🎃" },
    { nom: "courge musquée", emoji: "🎃" },
    { nom: "courge spaghetti", emoji: "🎃" },
    { nom: "courgette", emoji: "🥒" },
    { nom: "courgette jaune", emoji: "🥒" },
    { nom: "cresson", emoji: "🌿" },
    { nom: "crosne", emoji: "🍠" },
    { nom: "échalote", emoji: "🧅" },
    { nom: "échalote grise", emoji: "🧅" },
    { nom: "endive", emoji: "🥬" },
    { nom: "épinard", emoji: "🌿" },
    { nom: "épinard de nouvelle-zélande", emoji: "🌿" },
    { nom: "fenouil", emoji: "🌿" },
    { nom: "fève", emoji: "🫘" },
    { nom: "févettes", emoji: "🫘" },
    { nom: "frisée (salade)", emoji: "🥬" },
    { nom: "gombo", emoji: "🌿" },
    { nom: "haricot beurre", emoji: "🫘" },
    { nom: "haricot coco (frais)", emoji: "🫘" },
    { nom: "haricot kilomètre", emoji: "🫘" },
    { nom: "haricot mungo (pousses de soja)", emoji: "🌿" },
    { nom: "haricot plat", emoji: "🫘" },
    { nom: "haricot vert", emoji: "🫘" },
    { nom: "hélianthi", emoji: "🍠" },
    { nom: "igname", emoji: "🍠" },
    { nom: "laitue batavia", emoji: "🥬" },
    { nom: "laitue feuille de chêne", emoji: "🥬" },
    { nom: "laitue iceberg", emoji: "🥬" },
    { nom: "laitue romaine", emoji: "🥬" },
    { nom: "lentille fraîche", emoji: "🫘" },
    { nom: "luffa", emoji: "🥒" },
    { nom: "mâche", emoji: "🥬" },
    { nom: "maïs doux", emoji: "🌽" },
    { nom: "manioc", emoji: "🍠" },
    { nom: "margose (momordique)", emoji: "🥒" },
    { nom: "mertensia (huître végétale)", emoji: "🌿" },
    { nom: "navet blanc", emoji: "🍠" },
    { nom: "navet boule d'or", emoji: "🍠" },
    { nom: "navet daïkon", emoji: "🍠" },
    { nom: "oca du pérou", emoji: "🍠" },
    { nom: "oignon blanc", emoji: "🧅" },
    { nom: "oignon jaune", emoji: "🧅" },
    { nom: "oignon nouveau", emoji: "🧅" },
    { nom: "oignon rouge", emoji: "🧅" },
    { nom: "panais", emoji: "🍠" },
    { nom: "patate douce", emoji: "🍠" },
    { nom: "pâtisson", emoji: "🎃" },
    { nom: "persil tubéreux", emoji: "🌿" },
    { nom: "petit pois", emoji: "🫛" },
    { nom: "piment de cayenne", emoji: "🌶" },
    { nom: "piment d'espelette", emoji: "🌶" },
    { nom: "piment doux", emoji: "🫑" },
    { nom: "piment habanero", emoji: "🌶" },
    { nom: "piment jalapeño", emoji: "🌶" },
    { nom: "piment oiseau", emoji: "🌶" },
    { nom: "pissenlit", emoji: "🌿" },
    { nom: "poire de terre (yacon)", emoji: "🍠" },
    { nom: "poireau", emoji: "🥬" },
    { nom: "poireau d'été", emoji: "🥬" },
    { nom: "poireau perpétuel", emoji: "🥬" },
    { nom: "pois chiche (frais)", emoji: "🫘" },
    { nom: "pois gourmand (mangetout)", emoji: "🫛" },
    { nom: "poivron jaune", emoji: "🫑" },
    { nom: "poivron rouge", emoji: "🫑" },
    { nom: "poivron vert", emoji: "🫑" },
    { nom: "pomme de terre", emoji: "🥔" },
    { nom: "pomme de terre vitelotte", emoji: "🥔" },
    { nom: "potimarron", emoji: "🎃" },
    { nom: "potiron", emoji: "🎃" },
    { nom: "pourpier", emoji: "🌿" },
    { nom: "radicchio", emoji: "🥬" },
    { nom: "radis blanc", emoji: "🍠" },
    { nom: "radis glaçon", emoji: "🍠" },
    { nom: "radis noir", emoji: "🍠" },
    { nom: "radis rose", emoji: "🍠" },
    { nom: "roquette", emoji: "🥬" },
    { nom: "rutabaga", emoji: "🍠" },
    { nom: "salade (laitue classique)", emoji: "🥬" },
    { nom: "salsifis", emoji: "🍠" },
    { nom: "scarole", emoji: "🥬" },
    { nom: "scorsonère", emoji: "🍠" },
    { nom: "taro", emoji: "🍠" },
    { nom: "tétragone", emoji: "🌿" },
    { nom: "tomate cerise", emoji: "🍅" },
    { nom: "tomate cœur de bœuf", emoji: "🍅" },
    { nom: "tomate noire de crimée", emoji: "🍅" },
    { nom: "tomate roma", emoji: "🍅" },
    { nom: "tomate grappe", emoji: "🍅" },
    { nom: "topinambour", emoji: "🍠" },
    { nom: "trévise", emoji: "🥬" },
    { nom: "chou-palmiste (cœur de palmier)", emoji: "🌿" },
    { nom: "pousses de bambou", emoji: "🌿" },
    { nom: "pousses de fougère", emoji: "🌿" },
    { nom: "nopal (raquette de cactus)", emoji: "🌵" },
    { nom: "salicorne", emoji: "🌿" },
    { nom: "algue nori", emoji: "🌿" },
    { nom: "algue wakamé", emoji: "🌿" },
    { nom: "algue kombu", emoji: "🌿" },
    { nom: "algue dulse", emoji: "🌿" },
    { nom: "oignon grelot", emoji: "🧅" },
    { nom: "banane plantain", emoji: "🍌" },

    // Viandes
    { nom: "côte de bœuf", emoji: "🥩" },
    { nom: "entrecôte", emoji: "🥩" },
    { nom: "faux-filet", emoji: "🥩" },
    { nom: "filet de bœuf", emoji: "🥩" },
    { nom: "rumsteck", emoji: "🥩" },
    { nom: "bavette d'aloyau", emoji: "🥩" },
    { nom: "onglet de bœuf", emoji: "🥩" },
    { nom: "hampe de bœuf", emoji: "🥩" },
    { nom: "macreuse", emoji: "🥩" },
    { nom: "paleron de bœuf", emoji: "🥩" },
    { nom: "collier de bœuf", emoji: "🥩" },
    { nom: "plat de côtes de bœuf", emoji: "🥩" },
    { nom: "queue de bœuf", emoji: "🥩" },
    { nom: "langue de bœuf", emoji: "🥩" },
    { nom: "joue de bœuf", emoji: "🥩" },
    { nom: "cœur de bœuf", emoji: "🥩" },
    { nom: "foie de bœuf", emoji: "🥩" },
    { nom: "rognons de bœuf", emoji: "🥩" },
    { nom: "tripes de bœuf", emoji: "🥩" },
    { nom: "os à moelle", emoji: "🦴" },
    { nom: "rosbif", emoji: "🥩" },
    { nom: "escalope de veau", emoji: "🥩" },
    { nom: "côte de veau", emoji: "🥩" },
    { nom: "filet de veau", emoji: "🥩" },
    { nom: "jarret de veau", emoji: "🥩" },
    { nom: "tendron de veau", emoji: "🥩" },
    { nom: "poitrine de veau", emoji: "🥩" },
    { nom: "épaule de veau", emoji: "🥩" },
    { nom: "collier de veau", emoji: "🥩" },
    { nom: "ris de veau", emoji: "🥩" },
    { nom: "tête de veau", emoji: "🥩" },
    { nom: "foie de veau", emoji: "🥩" },
    { nom: "rognons de veau", emoji: "🥩" },
    { nom: "paupiette de veau", emoji: "🥩" },
    { nom: "côte de porc", emoji: "🥩" },
    { nom: "échine de porc", emoji: "🥩" },
    { nom: "filet mignon de porc", emoji: "🥩" },
    { nom: "travers de porc (ribs)", emoji: "🥩" },
    { nom: "poitrine de porc", emoji: "🥩" },
    { nom: "épaule de porc", emoji: "🥩" },
    { nom: "rouelle de porc", emoji: "🥩" },
    { nom: "jarret de porc", emoji: "🥩" },
    { nom: "pied de porc", emoji: "🥩" },
    { nom: "lard fumé", emoji: "🥓" },
    { nom: "lardons", emoji: "🥓" },
    { nom: "gigot d'agneau", emoji: "🍗" },
    { nom: "souris d'agneau", emoji: "🍗" },
    { nom: "épaule d'agneau", emoji: "🍗" },
    { nom: "côtelette d'agneau", emoji: "🍗" },
    { nom: "cuisse de poulet", emoji: "🍗" },
    { nom: "blanc de poulet", emoji: "🍗" },
    { nom: "filet de poulet", emoji: "🍗" },
    { nom: "pilon de poulet", emoji: "🍗" },
    { nom: "aile de poulet", emoji: "🍗" },
    { nom: "foie de poulet", emoji: "🍗" },
    { nom: "cuisse de dinde", emoji: "🍗" },
    { nom: "blanc de dinde", emoji: "🍗" },
    { nom: "escalope de dinde", emoji: "🍗" },
    { nom: "magret de canard", emoji: "🍗" },
    { nom: "cuisse de canard", emoji: "🍗" },
    { nom: "foie gras", emoji: "🦆" },
    { nom: "lapin", emoji: "🐇" },
    { nom: "sanglier", emoji: "🐗" },
    { nom: "chevreuil", emoji: "🦌" },
    { nom: "biche", emoji: "🦌" },
    { nom: "autruche", emoji: "🥩" },
    { nom: "cheval", emoji: "🥩" },
    { nom: "grenouille", emoji: "🐸" },
    { nom: "caille", emoji: "🍗" },
    { nom: "pigeon", emoji: "🍗" },
    { nom: "chair à saucisse", emoji: "🥩" },
    { nom: "saucisse de toulouse", emoji: "🌭" },
    { nom: "chipolata", emoji: "🌭" },
    { nom: "merguez", emoji: "🌭" },
    { nom: "andouillette", emoji: "🌭" },
    { nom: "boudin noir", emoji: "🌭" },
    { nom: "boudin blanc", emoji: "🌭" },
    { nom: "jambon blanc", emoji: "🥓" },
    { nom: "jambon cru", emoji: "🥓" },
    { nom: "chorizo", emoji: "🍕" },
    { nom: "saucisson sec", emoji: "🥓" },
    { nom: "steak haché", emoji: "🥩" },
    { nom: "saucisse de francfort", emoji: "🌭" },

    // Fruits
    { nom: "pomme", emoji: "🍎" },
    { nom: "pomme granny smith", emoji: "🍏" },
    { nom: "pomme golden", emoji: "🍎" },
    { nom: "poire", emoji: "🍐" },
    { nom: "pêche", emoji: "🍑" },
    { nom: "nectarine", emoji: "🍑" },
    { nom: "abricot", emoji: "🍑" },
    { nom: "prune", emoji: "🫐" },
    { nom: "reine-claude", emoji: "🫐" },
    { nom: "mirabelle", emoji: "🫐" },
    { nom: "cerise", emoji: "🍒" },
    { nom: "fraise", emoji: "🍓" },
    { nom: "framboise", emoji: "🍓" },
    { nom: "mûre", emoji: "🫐" },
    { nom: "myrtille", emoji: "🫐" },
    { nom: "cassis", emoji: "🫐" },
    { nom: "groseille", emoji: "🫐" },
    { nom: "airelle", emoji: "🫐" },
    { nom: "orange", emoji: "🍊" },
    { nom: "citron jaune", emoji: "🍋" },
    { nom: "citron vert (lime)", emoji: "🍋" },
    { nom: "pamplemousse", emoji: "🍊" },
    { nom: "clémentine", emoji: "🍊" },
    { nom: "kumquat", emoji: "🍊" },
    { nom: "melon", emoji: "🍈" },
    { nom: "pastèque", emoji: "🍉" },
    { nom: "raisin", emoji: "🍇" },
    { nom: "figue", emoji: "🫐" },
    { nom: "banane", emoji: "🍌" },
    { nom: "ananas", emoji: "🍍" },
    { nom: "mangue", emoji: "🥭" },
    { nom: "papaye", emoji: "🥭" },
    { nom: "noix de coco", emoji: "🥥" },
    { nom: "kiwi", emoji: "🥝" },
    { nom: "fruit de la passion", emoji: "🫐" },
    { nom: "grenade", emoji: "🍎" },
    { nom: "litchi", emoji: "🫐" },
    { nom: "carambole", emoji: "⭐" },
    { nom: "kaki", emoji: "🍅" },
    { nom: "pitaya (fruit du dragon)", emoji: "🌵" },
    { nom: "datte", emoji: "🫐" },
    { nom: "noix", emoji: "🥥" },
    { nom: "noisette", emoji: "🌰" },
    { nom: "amande", emoji: "🌰" },
    { nom: "pistache", emoji: "🌰" },
    { nom: "châtaigne", emoji: "🌰" },

    // Poissons & Fruits de mer
    { nom: "saumon frais", emoji: "🐟" },
    { nom: "saumon fumé", emoji: "🐟" },
    { nom: "truite", emoji: "🐟" },
    { nom: "truite fumée", emoji: "🐟" },
    { nom: "cabillaud", emoji: "🐟" },
    { nom: "lieu noir", emoji: "🐟" },
    { nom: "lieu jaune", emoji: "🐟" },
    { nom: "bar", emoji: "🐟" },
    { nom: "daurade", emoji: "🐟" },
    { nom: "sole", emoji: "🐟" },
    { nom: "turbot", emoji: "🐟" },
    { nom: "lotte", emoji: "🐟" },
    { nom: "merlu", emoji: "🐟" },
    { nom: "raie", emoji: "🐟" },
    { nom: "rouget", emoji: "🐟" },
    { nom: "sardine", emoji: "🐟" },
    { nom: "sardine en boîte", emoji: "🥫" },
    { nom: "maquereau", emoji: "🐟" },
    { nom: "maquereau fumé", emoji: "🐟" },
    { nom: "thon rouge", emoji: "🐟" },
    { nom: "thon albacore", emoji: "🐟" },
    { nom: "thon en boîte au naturel", emoji: "🥫" },
    { nom: "thon à l'huile", emoji: "🥫" },
    { nom: "anchois à l'huile", emoji: "🐟" },
    { nom: "anchois au sel", emoji: "🐟" },
    { nom: "hareng fumé", emoji: "🐟" },
    { nom: "haddock", emoji: "🐟" },
    { nom: "morue salée", emoji: "🐟" },
    { nom: "espadon", emoji: "🐟" },
    { nom: "flétan", emoji: "🐟" },
    { nom: "saint-pierre", emoji: "🐟" },
    { nom: "éperlan", emoji: "🐟" },
    { nom: "anguille", emoji: "🐟" },
    { nom: "brochet", emoji: "🐟" },
    { nom: "sandre", emoji: "🐟" },
    { nom: "carpe", emoji: "🐟" },
    { nom: "crevette rose", emoji: "🦐" },
    { nom: "crevette grise", emoji: "🦐" },
    { nom: "gambas", emoji: "🦐" },
    { nom: "langoustine", emoji: "🦞" },
    { nom: "homard", emoji: "🦞" },
    { nom: "langouste", emoji: "🦞" },
    { nom: "crabe", emoji: "🦀" },
    { nom: "tourteau", emoji: "🦀" },
    { nom: "araignée de mer", emoji: "🦀" },
    { nom: "chair de crabe", emoji: "🦀" },
    { nom: "noix de saint-jacques", emoji: "🐚" },
    { nom: "pétoncle", emoji: "🐚" },
    { nom: "moule", emoji: "🐚" },
    { nom: "huître", emoji: "🐚" },
    { nom: "coque", emoji: "🐚" },
    { nom: "palourde", emoji: "🐚" },
    { nom: "couteau de mer", emoji: "🐚" },
    { nom: "bulot", emoji: "🐚" },
    { nom: "bigorneau", emoji: "🐚" },
    { nom: "calamar", emoji: "🦑" },
    { nom: "encornet", emoji: "🦑" },
    { nom: "seiche", emoji: "🦑" },
    { nom: "poulpe", emoji: "🐙" },
    { nom: "œufs de lump", emoji: "🐟" },
    { nom: "caviar", emoji: "🐟" },
    { nom: "tarama", emoji: "🐟" },
    { nom: "surimi", emoji: "🦀" },

    // Ingrédients de base & Condiments
    { nom: "pâtes", emoji: "🍝" },
    { nom: "riz", emoji: "🍚" },
    { nom: "oeufs", emoji: "🥚" },
    { nom: "sucre", emoji: "🍚" },
    { nom: "farine", emoji: "🌾" },
    { nom: "lait", emoji: "🥛" },
    { nom: "beurre", emoji: "🧈" },
    { nom: "fromage", emoji: "🧀" },
    { nom: "chocolat", emoji: "🍫" },
    { nom: "sauce soja", emoji: "🍶" },
    { nom: "kub'or", emoji: "🧊" },
    { nom: "sel fin", emoji: "🧂" },
    { nom: "gros sel", emoji: "🧂" },
    { nom: "fleur de sel", emoji: "🧂" },
    { nom: "sel au céleri", emoji: "🧂" },
    { nom: "poivre noir en grains", emoji: "🧂" },
    { nom: "poivre blanc", emoji: "🧂" },
    { nom: "poivre vert", emoji: "🧂" },
    { nom: "poivre de sichuan", emoji: "🧂" },
    { nom: "poivre de kampot", emoji: "🧂" },
    { nom: "baies roses", emoji: "🧂" },
    { nom: "cannelle en poudre", emoji: "🧂" },
    { nom: "bâton de cannelle", emoji: "🧂" },
    { nom: "cumin en poudre", emoji: "🧂" },
    { nom: "graines de cumin", emoji: "🧂" },
    { nom: "coriandre en poudre", emoji: "🧂" },
    { nom: "graines de coriandre", emoji: "🧂" },
    { nom: "curcuma", emoji: "🧂" },
    { nom: "curry en poudre", emoji: "🧂" },
    { nom: "pâte de curry rouge", emoji: "🍶" },
    { nom: "pâte de curry vert", emoji: "🍶" },
    { nom: "pâte de curry jaune", emoji: "🍶" },
    { nom: "garam masala", emoji: "🧂" },
    { nom: "ras el hanout", emoji: "🧂" },
    { nom: "colombo", emoji: "🧂" },
    { nom: "tandoori", emoji: "🧂" },
    { nom: "paprika doux", emoji: "🧂" },
    { nom: "paprika fumé", emoji: "🧂" },
    { nom: "piment d'espelette en poudre", emoji: "🧂" },
    { nom: "piment de cayenne en poudre", emoji: "🧂" },
    { nom: "clou de girofle", emoji: "🧂" },
    { nom: "noix de muscade", emoji: "🧂" },
    { nom: "macis", emoji: "🧂" },
    { nom: "cardamome verte", emoji: "🧂" },
    { nom: "cardamome noire", emoji: "🧂" },
    { nom: "gingembre en poudre", emoji: "🧂" },
    { nom: "anis étoilé", emoji: "🧂" },
    { nom: "badiane", emoji: "🧂" },
    { nom: "graines de fenouil", emoji: "🧂" },
    { nom: "aneth séché", emoji: "🌿" },
    { nom: "basilic séché", emoji: "🌿" },
    { nom: "origan séché", emoji: "🌿" },
    { nom: "thym séché", emoji: "🌿" },
    { nom: "laurier", emoji: "🍃" },
    { nom: "romarin séché", emoji: "🌿" },
    { nom: "sauge séchée", emoji: "🌿" },
    { nom: "estragon séché", emoji: "🌿" },
    { nom: "sarriette", emoji: "🌿" },
    { nom: "marjolaine", emoji: "🌿" },
    { nom: "ciboulette séchée", emoji: "🌿" },
    { nom: "persil séché", emoji: "🌿" },
    { nom: "menthe séchée", emoji: "🌿" },
    { nom: "safran en pistils", emoji: "🧂" },
    { nom: "safran en poudre", emoji: "🧂" },
    { nom: "gousse de vanille", emoji: "🍦" },
    { nom: "extrait de vanille", emoji: "🍶" },
    { nom: "sésame blanc", emoji: "🧂" },
    { nom: "sésame noir", emoji: "🧂" },
    { nom: "graines de pavot", emoji: "🧂" },
    { nom: "graines de lin", emoji: "🧂" },
    { nom: "graines de tournesol", emoji: "🧂" },
    { nom: "graines de courge", emoji: "🧂" },
    { nom: "graines de chia", emoji: "🧂" },
    { nom: "graines de moutarde", emoji: "🧂" },
    { nom: "pignons de pin", emoji: "🧂" },
    
    // Huiles & Vinaigres
    { nom: "huile d'olive extra vierge", emoji: "🍶" },
    { nom: "huile de tournesol", emoji: "🍶" },
    { nom: "huile de colza", emoji: "🍶" },
    { nom: "huile de pépins de raisin", emoji: "🍶" },
    { nom: "huile de sésame", emoji: "🍶" },
    { nom: "huile de noix", emoji: "🍶" },
    { nom: "huile de noisette", emoji: "🍶" },
    { nom: "huile d'arachide", emoji: "🍶" },
    { nom: "huile d'avocat", emoji: "🍶" },
    { nom: "huile d'argan", emoji: "🍶" },
    { nom: "huile de truffe", emoji: "🍶" },
    { nom: "vinaigre de vin rouge", emoji: "🍶" },
    { nom: "vinaigre de vin blanc", emoji: "🍶" },
    { nom: "vinaigre balsamique", emoji: "🍶" },
    { nom: "crème de balsamique", emoji: "🍶" },
    { nom: "vinaigre de cidre", emoji: "🍶" },
    { nom: "vinaigre d'alcool", emoji: "🍶" },
    { nom: "vinaigre de xérès", emoji: "🍶" },
    { nom: "vinaigre de riz", emoji: "🍶" },
    { nom: "vinaigre de framboise", emoji: "🍶" },
    
    // Produits Laitiers & Œufs
    { nom: "œuf entier", emoji: "🥚" },
    { nom: "blanc d'œuf", emoji: "🥚" },
    { nom: "jaune d'œuf", emoji: "🥚" },
    { nom: "œuf de caille", emoji: "🥚" },
    { nom: "beurre doux", emoji: "🧈" },
    { nom: "beurre demi-sel", emoji: "🧈" },
    { nom: "beurre clarifié", emoji: "🧈" },
    { nom: "ghee", emoji: "🧈" },
    { nom: "margarine", emoji: "🧈" },
    { nom: "crème fraîche épaisse", emoji: "🥛" },
    { nom: "crème fraîche liquide", emoji: "🥛" },
    { nom: "crème fleurette", emoji: "🥛" },
    { nom: "crème de soja", emoji: "🥛" },
    { nom: "crème de coco", emoji: "🥛" },
    { nom: "lait entier", emoji: "🥛" },
    { nom: "lait demi-écrémé", emoji: "🥛" },
    { nom: "lait écrémé", emoji: "🥛" },
    { nom: "lait en poudre", emoji: "🥛" },
    { nom: "lait concentré sucré", emoji: "🥛" },
    { nom: "lait concentré non sucré", emoji: "🥛" },
    { nom: "lait d'amande", emoji: "🥛" },
    { nom: "lait de soja", emoji: "🥛" },
    { nom: "lait d'avoine", emoji: "🥛" },
    { nom: "lait de riz", emoji: "🥛" },
    { nom: "lait de coco", emoji: "🥛" },
    { nom: "babeurre", emoji: "🥛" },
    { nom: "yaourt nature", emoji: "🍦" },
    { nom: "yaourt grec", emoji: "🍦" },
    { nom: "yaourt de brebis", emoji: "🍦" },
    { nom: "fromage blanc", emoji: "🍦" },
    { nom: "faisselle", emoji: "🍦" },
    { nom: "mascarpone", emoji: "🧀" },
    { nom: "ricotta", emoji: "🧀" },
    { nom: "mozzarella di bufala", emoji: "🧀" },
    { nom: "burrata", emoji: "🧀" },
    { nom: "stracciatella", emoji: "🧀" },
    { nom: "pecorino", emoji: "🧀" },
    { nom: "grana padano", emoji: "🧀" },
    { nom: "emmental râpé", emoji: "🧀" },
    { nom: "gruyère", emoji: "🧀" },
    { nom: "comté", emoji: "🧀" },
    { nom: "beaufort", emoji: "🧀" },
    { nom: "cantal", emoji: "🧀" },
    { nom: "salers", emoji: "🧀" },
    { nom: "laguiole", emoji: "🧀" },
    { nom: "cheddar", emoji: "🧀" },
    { nom: "gouda", emoji: "🧀" },
    { nom: "mimolette", emoji: "🧀" },
    { nom: "edam", emoji: "🧀" },
    { nom: "roquefort", emoji: "🧀" },
    { nom: "bleu d'auvergne", emoji: "🧀" },
    { nom: "fourme d'ambert", emoji: "🧀" },
    { nom: "gorgonzola", emoji: "🧀" },
    { nom: "stilton", emoji: "🧀" },
    { nom: "camembert", emoji: "🧀" },
    { nom: "brie de meaux", emoji: "🧀" },
    { nom: "brie de melun", emoji: "🧀" },
    { nom: "coulommiers", emoji: "🧀" },
    { nom: "pont-l'évêque", emoji: "🧀" },
    { nom: "livarot", emoji: "🧀" },
    { nom: "munster", emoji: "🧀" },
    { nom: "maroilles", emoji: "🧀" },
    { nom: "époisses", emoji: "🧀" },
    { nom: "reblochon", emoji: "🧀" },
    { nom: "morbier", emoji: "🧀" },
    { nom: "raclette", emoji: "🧀" },
    { nom: "tartiflette", emoji: "🧀" },
    { nom: "mont d'or", emoji: "🧀" },
    { nom: "vacherin", emoji: "🧀" },
    { nom: "feta", emoji: "🧀" },
    { nom: "halloumi", emoji: "🧀" },
    { nom: "paneer", emoji: "🧀" },
    { nom: "fromage à tartiner", emoji: "🧀" },
    { nom: "boursin", emoji: "🧀" },
    { nom: "chèvre frais", emoji: "🧀" },
    { nom: "bûche de chèvre", emoji: "🧀" },
    { nom: "crottin de chavignol", emoji: "🧀" },
    { nom: "rocamadour", emoji: "🧀" },
    { nom: "picodon", emoji: "🧀" },
    { nom: "pelardon", emoji: "🧀" },
    { nom: "valençay", emoji: "🧀" },
    { nom: "ossau-iraty", emoji: "🧀" },
    { nom: "tomme de savoie", emoji: "🧀" },
    { nom: "tomme de brebis", emoji: "🧀" },

    // Légumineuses, Céréales & Graines
    { nom: "lentilles vertes", emoji: "🫘" },
    { nom: "lentilles corail", emoji: "🫘" },
    { nom: "lentilles beluga", emoji: "🫘" },
    { nom: "pois chiches", emoji: "🫘" },
    { nom: "haricots rouges", emoji: "🫘" },
    { nom: "haricots blancs", emoji: "🫘" },
    { nom: "quinoa", emoji: "🌾" },
    { nom: "boulgour", emoji: "🌾" },
    { nom: "semoule de blé", emoji: "🌾" },
    { nom: "polenta", emoji: "🌽" },
    { nom: "avoine", emoji: "🌾" },
    { nom: "sarrasin", emoji: "🌾" },
    { nom: "orge perlée", emoji: "🌾" },
    { nom: "graines de tournesol", emoji: "🌻" },
    { nom: "graines de courge", emoji: "🎃" },
    { nom: "graines de lin", emoji: "🌾" },
    { nom: "graines de chia", emoji: "🌾" },
    { nom: "graines de sésame", emoji: "🧂" },
    { nom: "pignons de pin", emoji: "🌲" }
];

// Export pour Node.js si nécessaire (tests)
if (typeof module !== 'undefined') {
    module.exports = {
        recipes: recipes,
        commonIngredients: commonIngredients
    };
}



